[nushell.files]
"src/nushell" = "~/AppData/Roaming/nushell"

[wezterm.files]
"src/wezterm" = "~/.config/wezterm/"

[gitui.files]
"src/gitui" = "~/AppData/Roaming/gitui"

[powershell.files]
"src/PowerShell" = "~/Documents/PowerShell"

[starship.files]
"src/starship/starship.toml" = "~/.config/starship.toml"

[nzskkserv.files]
"src/nzskkserv" = "~/AppData/Roaming/nzskkserv/config"

[corvusskk.files]
"src/corvusskk/config.xml" = "~/AppData/Roaming/CorvusSKK/config.xml"

# for msys

[fish.files]
"src/fish" = "~/.config/fish/"

[bash.files]
"src/bash-msys" = "~/"
