# common
[nushell.files]

[wezterm.files]

[gitui.files]

[starship.files]

# linux only
[bash.files]

[zsh.files]

[tmux.files]

# windows only
[nzskkserv.files]

[corvusskk.files]

[powershell.files]
